import { SurfSpot } from './types';

export const SURF_SPOTS: SurfSpot[] = [
  // === COSTA RICA (PACIFIC) ===
  {
    id: 'witch-rock',
    name: "Witch's Rock",
    region: 'Costa Rica',
    country: 'CR',
    latitude: 10.79,
    longitude: -85.82,
    facing: 270,
    idealSwellDir: [200, 290],
    idealSwellSize: [1.0, 3.0],
    type: 'beach',
    description: 'World-class beach break in Santa Rosa National Park. Boat access only. Powerful, hollow waves.',
  },
  {
    id: 'ollies-point',
    name: "Ollie's Point",
    region: 'Costa Rica',
    country: 'CR',
    latitude: 10.80,
    longitude: -85.80,
    facing: 290,
    idealSwellDir: [220, 310],
    idealSwellSize: [0.8, 2.5],
    type: 'point',
    description: 'Perfect right-hand point break. Boat access only. Long, peeling walls.',
  },
  {
    id: 'playa-grande',
    name: 'Playa Grande',
    region: 'Costa Rica',
    country: 'CR',
    latitude: 10.33,
    longitude: -85.85,
    facing: 270,
    idealSwellDir: [210, 290],
    idealSwellSize: [0.8, 2.5],
    type: 'beach',
    description: 'Consistent beach break with multiple peaks. One of the best waves in Guanacaste.',
  },
  {
    id: 'tamarindo',
    name: 'Tamarindo',
    region: 'Costa Rica',
    country: 'CR',
    latitude: 10.30,
    longitude: -85.84,
    facing: 265,
    idealSwellDir: [200, 280],
    idealSwellSize: [0.5, 2.0],
    type: 'beach',
    description: 'Beginner-friendly beach break with rivermouth peaks. Consistent and accessible.',
  },
  {
    id: 'playa-avellanas',
    name: 'Playa Avellanas',
    region: 'Costa Rica',
    country: 'CR',
    latitude: 10.26,
    longitude: -85.84,
    facing: 270,
    idealSwellDir: [210, 290],
    idealSwellSize: [0.8, 2.5],
    type: 'beach',
    description: 'Powerful beach break with "Little Hawaii" section. Multiple peaks for all levels.',
  },
  {
    id: 'playa-negra',
    name: 'Playa Negra',
    region: 'Costa Rica',
    country: 'CR',
    latitude: 10.22,
    longitude: -85.83,
    facing: 270,
    idealSwellDir: [220, 290],
    idealSwellSize: [0.8, 2.5],
    type: 'reef',
    description: 'Fast, hollow left-hand reef break. Featured in Endless Summer II. Advanced surfers.',
  },
  {
    id: 'nosara',
    name: 'Nosara (Playa Guiones)',
    region: 'Costa Rica',
    country: 'CR',
    latitude: 9.94,
    longitude: -85.67,
    facing: 270,
    idealSwellDir: [210, 280],
    idealSwellSize: [0.6, 2.0],
    type: 'beach',
    description: 'Long, consistent beach break. Great for all levels. Reliable year-round waves.',
  },
  {
    id: 'santa-teresa',
    name: 'Santa Teresa',
    region: 'Costa Rica',
    country: 'CR',
    latitude: 9.64,
    longitude: -85.17,
    facing: 260,
    idealSwellDir: [200, 280],
    idealSwellSize: [0.6, 2.5],
    type: 'beach',
    description: 'Consistent beach break with reef sections. Popular surf town. Great waves year-round.',
  },
  {
    id: 'mal-pais',
    name: 'Mal País',
    region: 'Costa Rica',
    country: 'CR',
    latitude: 9.59,
    longitude: -85.15,
    facing: 250,
    idealSwellDir: [200, 270],
    idealSwellSize: [0.6, 2.5],
    type: 'reef',
    description: 'Rocky reef and point break south of Santa Teresa. More advanced waves.',
  },
  {
    id: 'jaco',
    name: 'Jacó',
    region: 'Costa Rica',
    country: 'CR',
    latitude: 9.62,
    longitude: -84.63,
    facing: 270,
    idealSwellDir: [200, 280],
    idealSwellSize: [0.5, 2.0],
    type: 'beach',
    description: 'Accessible beach break close to San José. Consistent but can be mushy.',
  },
  {
    id: 'playa-hermosa-jaco',
    name: 'Playa Hermosa (Jacó)',
    region: 'Costa Rica',
    country: 'CR',
    latitude: 9.56,
    longitude: -84.58,
    facing: 260,
    idealSwellDir: [200, 280],
    idealSwellSize: [1.0, 3.5],
    type: 'beach',
    description: 'Powerful, heavy beach break. Hosts ISA World Championships. Expert-level waves.',
  },
  {
    id: 'dominical',
    name: 'Dominical',
    region: 'Costa Rica',
    country: 'CR',
    latitude: 9.25,
    longitude: -83.86,
    facing: 250,
    idealSwellDir: [190, 270],
    idealSwellSize: [0.8, 3.0],
    type: 'beach',
    description: 'Powerful rivermouth beach break. Can get heavy. Best on S swells.',
  },
  {
    id: 'pavones',
    name: 'Pavones',
    region: 'Costa Rica',
    country: 'CR',
    latitude: 8.39,
    longitude: -83.16,
    facing: 230,
    idealSwellDir: [180, 240],
    idealSwellSize: [1.0, 3.0],
    type: 'point',
    description: 'One of the longest left-hand point breaks in the world. Needs solid S swell.',
  },

  // === HAWAII ===
  {
    id: 'pipeline',
    name: 'Pipeline',
    region: 'Hawaii',
    country: 'US',
    latitude: 21.67,
    longitude: -158.05,
    facing: 340,
    idealSwellDir: [300, 360],
    idealSwellSize: [1.5, 5.0],
    type: 'reef',
    description: 'The most famous wave in the world. Heavy, barreling left over shallow reef.',
  },
  {
    id: 'sunset-beach',
    name: 'Sunset Beach',
    region: 'Hawaii',
    country: 'US',
    latitude: 21.68,
    longitude: -158.04,
    facing: 335,
    idealSwellDir: [290, 350],
    idealSwellSize: [1.5, 5.0],
    type: 'reef',
    description: 'Big wave arena on the North Shore. Massive open-ocean swells.',
  },
  {
    id: 'waimea',
    name: 'Waimea Bay',
    region: 'Hawaii',
    country: 'US',
    latitude: 21.64,
    longitude: -158.07,
    facing: 350,
    idealSwellDir: [310, 360],
    idealSwellSize: [2.5, 8.0],
    type: 'beach',
    description: 'Legendary big wave spot. Only breaks on large NW swells (15ft+).',
  },
  {
    id: 'jaws',
    name: 'Jaws (Peahi)',
    region: 'Hawaii',
    country: 'US',
    latitude: 20.94,
    longitude: -156.22,
    facing: 350,
    idealSwellDir: [310, 360],
    idealSwellSize: [4.0, 15.0],
    type: 'reef',
    description: 'Big wave tow-in spot on Maui. Among the largest rideable waves on Earth.',
  },

  // === CALIFORNIA ===
  {
    id: 'mavericks',
    name: 'Mavericks',
    region: 'California',
    country: 'US',
    latitude: 37.49,
    longitude: -122.50,
    facing: 270,
    idealSwellDir: [270, 320],
    idealSwellSize: [3.0, 10.0],
    type: 'reef',
    description: 'Notorious big wave spot near Half Moon Bay. Cold water, sharks, massive waves.',
  },
  {
    id: 'steamer-lane',
    name: 'Steamer Lane',
    region: 'California',
    country: 'US',
    latitude: 36.95,
    longitude: -122.03,
    facing: 230,
    idealSwellDir: [250, 310],
    idealSwellSize: [1.0, 3.5],
    type: 'point',
    description: 'Iconic Santa Cruz point break. Multiple takeoff zones. Classic California wave.',
  },
  {
    id: 'trestles',
    name: 'Trestles',
    region: 'California',
    country: 'US',
    latitude: 33.38,
    longitude: -117.59,
    facing: 230,
    idealSwellDir: [190, 260],
    idealSwellSize: [0.8, 2.5],
    type: 'reef',
    description: 'World-class cobblestone point breaks. Multiple peaks (Lowers, Uppers, etc.).',
  },
  {
    id: 'rincon',
    name: 'Rincon',
    region: 'California',
    country: 'US',
    latitude: 34.37,
    longitude: -119.48,
    facing: 200,
    idealSwellDir: [240, 300],
    idealSwellSize: [1.0, 3.0],
    type: 'point',
    description: '"Queen of the Coast." Perfect right-hand point break. Best in winter NW swells.',
  },
  {
    id: 'huntington',
    name: 'Huntington Beach',
    region: 'California',
    country: 'US',
    latitude: 33.66,
    longitude: -118.00,
    facing: 230,
    idealSwellDir: [190, 260],
    idealSwellSize: [0.6, 2.0],
    type: 'beach',
    description: '"Surf City USA." Consistent beach break at the pier. Home of the US Open.',
  },

  // === MEXICO ===
  {
    id: 'puerto-escondido',
    name: 'Puerto Escondido',
    region: 'Mexico',
    country: 'MX',
    latitude: 15.86,
    longitude: -97.07,
    facing: 200,
    idealSwellDir: [170, 220],
    idealSwellSize: [1.5, 5.0],
    type: 'beach',
    description: '"Mexican Pipeline." Heavy, hollow beach break. One of the heaviest waves on Earth.',
  },
  {
    id: 'sayulita',
    name: 'Sayulita',
    region: 'Mexico',
    country: 'MX',
    latitude: 20.87,
    longitude: -105.44,
    facing: 270,
    idealSwellDir: [230, 290],
    idealSwellSize: [0.5, 2.0],
    type: 'point',
    description: 'Fun right-hand point break. Great for beginners and intermediates.',
  },

  // === EUROPE ===
  {
    id: 'nazare',
    name: 'Nazaré',
    region: 'Europe',
    country: 'PT',
    latitude: 39.60,
    longitude: -9.07,
    facing: 300,
    idealSwellDir: [280, 340],
    idealSwellSize: [3.0, 20.0],
    type: 'beach',
    description: 'Home of the world record biggest wave ever surfed. Underwater canyon amplifies swells.',
  },
  {
    id: 'hossegor',
    name: 'Hossegor',
    region: 'Europe',
    country: 'FR',
    latitude: 43.67,
    longitude: -1.44,
    facing: 280,
    idealSwellDir: [270, 320],
    idealSwellSize: [1.0, 3.0],
    type: 'beach',
    description: 'Heavy beach break in southwest France. Hosts WSL Championship Tour event.',
  },
  {
    id: 'mundaka',
    name: 'Mundaka',
    region: 'Europe',
    country: 'ES',
    latitude: 43.41,
    longitude: -2.70,
    facing: 340,
    idealSwellDir: [300, 350],
    idealSwellSize: [1.0, 3.0],
    type: 'point',
    description: 'Legendary left-hand rivermouth barrel in Basque Country. When it works, it\'s world-class.',
  },
  {
    id: 'peniche',
    name: 'Peniche (Supertubos)',
    region: 'Europe',
    country: 'PT',
    latitude: 39.35,
    longitude: -9.37,
    facing: 270,
    idealSwellDir: [260, 320],
    idealSwellSize: [1.0, 3.0],
    type: 'beach',
    description: 'Powerful, hollow beach break. Hosts WSL Championship Tour. "European Pipeline."',
  },

  // === INDONESIA ===
  {
    id: 'uluwatu',
    name: 'Uluwatu',
    region: 'Indonesia',
    country: 'ID',
    latitude: -8.81,
    longitude: 115.09,
    facing: 220,
    idealSwellDir: [180, 230],
    idealSwellSize: [1.0, 3.5],
    type: 'reef',
    description: 'World-class left-hand reef break in Bali. Multiple sections from 4-12ft.',
  },
  {
    id: 'padang-padang',
    name: 'Padang Padang',
    region: 'Indonesia',
    country: 'ID',
    latitude: -8.81,
    longitude: 115.10,
    facing: 220,
    idealSwellDir: [190, 240],
    idealSwellSize: [1.5, 3.5],
    type: 'reef',
    description: 'Heavy, barreling left in Bali. Needs solid S swell to break properly.',
  },
  {
    id: 'g-land',
    name: 'G-Land (Grajagan)',
    region: 'Indonesia',
    country: 'ID',
    latitude: -8.74,
    longitude: 114.37,
    facing: 210,
    idealSwellDir: [190, 240],
    idealSwellSize: [1.5, 4.0],
    type: 'reef',
    description: 'Remote left-hand reef break in East Java. Long, perfect barrels.',
  },

  // === AUSTRALIA ===
  {
    id: 'snapper-rocks',
    name: 'Snapper Rocks',
    region: 'Australia',
    country: 'AU',
    latitude: -28.17,
    longitude: 153.55,
    facing: 90,
    idealSwellDir: [70, 140],
    idealSwellSize: [0.8, 2.5],
    type: 'point',
    description: 'Superbank right-hand sand point. Can link 300m+ rides. Gold Coast gem.',
  },
  {
    id: 'bells-beach',
    name: 'Bells Beach',
    region: 'Australia',
    country: 'AU',
    latitude: -38.37,
    longitude: 144.28,
    facing: 210,
    idealSwellDir: [190, 250],
    idealSwellSize: [1.0, 3.5],
    type: 'reef',
    description: 'Iconic Australian wave. Home of the Rip Curl Pro since 1973.',
  },

  // === SOUTH AFRICA ===
  {
    id: 'jeffreys-bay',
    name: "Jeffreys Bay",
    region: 'South Africa',
    country: 'ZA',
    latitude: -34.03,
    longitude: 24.93,
    facing: 130,
    idealSwellDir: [120, 190],
    idealSwellSize: [1.0, 3.5],
    type: 'point',
    description: 'One of the best right-hand point breaks on Earth. Supertubes section is world-class.',
  },

  // === TAHITI ===
  {
    id: 'teahupoo',
    name: "Teahupo'o",
    region: 'Tahiti',
    country: 'PF',
    latitude: -17.85,
    longitude: -149.26,
    facing: 210,
    idealSwellDir: [180, 230],
    idealSwellSize: [1.5, 5.0],
    type: 'reef',
    description: 'The heaviest wave on the planet. Thick, mutant barrels over shallow reef. 2024 Olympic venue.',
  },
];

export const REGIONS = [...new Set(SURF_SPOTS.map((s) => s.region))];

export function getSpotsByRegion(region: string): SurfSpot[] {
  return SURF_SPOTS.filter((s) => s.region === region);
}

export function getSpotById(id: string): SurfSpot | undefined {
  return SURF_SPOTS.find((s) => s.id === id);
}
